### ISSUE TITLE
Program launch

### ISSUE THREAD

**Issue by DocG-code** [xalexalex/via#1]
Hey not sure how active this project is. I like the concept of this script, especially opening files and directories. However I'm unable to find a way to launch programs in a way that "dmenu_run* does. Let me know if I'm missing how to configure the script in a way that I haven't been able to find in the README yet.

**Comment by xalexalex** [comment]
Hey!
`via` doesn't scan `$PATH` for executables like `dmenu` does, and it doesn't scan .desktop files either. However, you'll find that most of the times you launch a program to open a file, and with `via` you can just pick the file and you'll get it done in a single action.

However, you may have some programs that you want to launch by themselves, without file arguments. For me—for example—these include:

- `passmenu`
- `passmenu --type`
- `anki`
- `ImageJ-linux64`

And I add them manually to `~/.config/via/shortcuts` (this happens perhaps once every few months).

Let me know if this answers your question and I hope you like `via`!
