### ISSUE TITLE
Trying to open files in vim

### ISSUE THREAD

**Issue by samuelj123** [xalexalex/via#2]
I'm trying to use via to open certain md/txt files using vim on my urxvt terminal.
I tried editing line 15 of via-open using all the possible arguments I could find online, but I can't seem to be able to work. 
What terminal emulator do you use? If not, what else would you suggest?

Edit: I discovered this problem only arises with rofi -dmenu. 
With urxvt line 15 looks like 
`$TERMINAL -e $EDITOR "$arg" `

**Comment by xalexalex** [comment]
Hey,
I can't reproduce the issue. I use `st` as terminal and `dmenu`, but even using `urxvt` and `rofi -dmenu` everything works as expected. You should make sure that `via-open` runs `urxvt -e vim "$arg"` for `*.txt`.
Just to be sure, if you run `urxvt -e vim somefile.txt` in a terminal, does it work as intended?
If it still doesn't work I'll be glad to look into your files to see if I can help.

**Comment by samuelj123** [comment]
Both dmenu and rofi runs `urxvt -e vim "$arg"` perfectly. I just tried it out. I guess, I'm not feeding in the variables into my bashrc correctly. Will look into that later.  
Thanks a lot for your inputs and timely help!  

Also, I just have to add... this is a kick-ass script! It's so wonderfully elegant!
