### ISSUE TITLE
Is this script still working?

### ISSUE THREAD

**Issue by ecribia** [xalexalex/via#4]
Hi, i have some trouble getting this script to work. When i write via in the terminal i get a message for dmenu with its options in the terminal printed out. Dont really know what im doing wrong here

**Comment by xalexalex** [comment]
Yes, it works and I still use it daily! You are most likely invoking dmenu
with wrong arguments. Is your via-menu script fine? Does something like "$
echo -e 'a\nb\nc' | ./via-menu" work?

**Comment by ecribia** [comment]
I unfortunately cant get it to work :/ But its probably me who is being stupid. Im very new to dmenu in general. What ive done is:

clone repo
make install
copied the three configs to .config/via
added it to my PATH

When i try to run via (or via-menu) through the terminal, i get "usage: dmenu [-bfiv]... etc"... am i using the tool in a wrong way?

Im using a few patches with dmenu, so dont know if that could be a reason why its not working?

**Comment by xalexalex** [comment]
The patches might be the problem. You should either fix the arguments to
dmenu in ~/.config/via/via-menu to match your patched dmenu or try with an
unpatched dmenu

**Comment by ecribia** [comment]
Thanks, i will try both those things and see if it helps :)

**Comment by ecribia** [comment]
Update: Got it to work! You were right the problem was in via-menu. My dmenu doesnt like the -i flag so when i removed it, it worked :) Thanks!

**Comment by xalexalex** [comment]
Amazing! Have fun :)
